[package]
name = "o"
version = "0.1.0"
authors = ["Ignacio Carbajo <icarbajop@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2.32"
csv = "1"
dirs = "1.0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
